Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 2, in <module>
    from .eval_metrics import categorical_accuracy_continuous_tolerance_score, get_acc_and_bac, feature_wise_accuracy_score, batch_feature_wise_accuracy_score
  File "/home/luser/chirag/tableak/utils/eval_metrics.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/luser/chirag/tableak/run_fed_avg_attacks.py", line 2, in <module>
    import attacks
  File "/home/luser/chirag/tableak/attacks/__init__.py", line 1, in <module>
    from .gradient_inversion_attack import invert_grad
  File "/home/luser/chirag/tableak/attacks/gradient_inversion_attack.py", line 3, in <module>
    from utils import categorical_gumbel_softmax_sampling, categorical_softmax, create_feature_mask, \
  File "/home/luser/chirag/tableak/utils/__init__.py", line 1, in <module>
    from .encoder_decoder import to_numeric, to_categorical
  File "/home/luser/chirag/tableak/utils/encoder_decoder.py", line 1, in <module>
    import numpy as np
  File "/root/anaconda3/lib/python3.11/site-packages/numpy/__init__.py", line 149, in <module>
    from . import lib
  File "/root/anaconda3/lib/python3.11/site-packages/numpy/lib/__init__.py", line 23, in <module>
    from . import index_tricks
  File "/root/anaconda3/lib/python3.11/site-packages/numpy/lib/index_tricks.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "/root/anaconda3/lib/python3.11/site-packages/numpy/matrixlib/__init__.py", line 4, in <module>
    from . import defmatrix
  File "/root/anaconda3/lib/python3.11/site-packages/numpy/matrixlib/defmatrix.py", line 12, in <module>
    from numpy.linalg import matrix_power
  File "/root/anaconda3/lib/python3.11/site-packages/numpy/linalg/__init__.py", line 73, in <module>
    from . import linalg
  File "/root/anaconda3/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 37, in <module>
    from numpy._typing import NDArray
  File "/root/anaconda3/lib/python3.11/site-packages/numpy/_typing/__init__.py", line 182, in <module>
    from ._array_like import (
  File "/root/anaconda3/lib/python3.11/site-packages/numpy/_typing/_array_like.py", line 96, in <module>
    _ArrayLikeBool_co = _DualArrayLike[
                        ^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/typing.py", line 355, in inner
    return cached(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/typing.py", line 1408, in __getitem__
    new_args = self._determine_new_args(args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/typing.py", line 1439, in _determine_new_args
    return tuple(self._make_substitution(self.__args__, new_arg_by_param))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/typing.py", line 1463, in _make_substitution
    new_arg = old_arg[tuple(subargs)]
              ~~~~~~~^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/typing.py", line 355, in inner
    return cached(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/typing.py", line 1409, in __getitem__
    r = self.copy_with(new_args)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/typing.py", line 1504, in copy_with
    return self.__class__(self.__origin__, args, name=self._name, inst=self._inst,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/typing.py", line 1355, in __init__
    super().__init__(origin, inst=inst, name=name)
  File "/root/anaconda3/lib/python3.11/typing.py", line 1262, in __init__
    self.__slots__ = None  # This is not documented.
    ^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/typing.py", line 1298, in __setattr__
    if _is_dunder(attr) or attr in {'_name', '_inst', '_nparams',
       ^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/typing.py", line 1246, in _is_dunder
    return attr.startswith('__') and attr.endswith('__')
           ^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Traceback (most recent call last):
  File "50_clients_tableak.py", line 16, in <module>
    subprocess.run(["python", "run_fed_avg_attacks.py", "--experiment", "52", "--name_state", state_code])
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
